#' Sample VEP file.
#'
#' A ramdomly generated data for VEP. Includes training data size, predicted
#' values for non-augmented and augmented training data model and actual value.
#' Contains 1000 data.
#'
#' @source generated by Shuzo Fukunaga
#'
#' @format A dataframe with 1000 rows.
#' \describe{
#'    \item{data_size}{A size of training data.}
#'    \item{non_augmented_value}{A predicted value with non-augmented training
#'    data}
#'    \item{augmented_value}{A predicted value with augmented training data}
#'    \item{actual_value}{A actual value the machine learning model is
#'    predicting}
#' }
#'
#' @examples
#' \dontrun{
#' sampleRandomData
#' }
"sampleRandomData"

# [END]
